{{- with .Values.secretProviderClass }}
{{- if .enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $.Release.Name }}
  labels:
    {{- include "nf.labels" $ | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ required "secretProviderClass.clientID" .clientID | quote }}
    tenantId: {{ required "secretProviderClass.tenantId" .tenantId | quote }}
    keyvaultName: {{ required "secretProviderClass.keyvaultName" .keyvaultName | quote }}
    objects: |
      array:
      {{- range $name, $_ := .objects }}
        - |
          objectName: {{ $name }}
          objectType: secret
      {{- end }}
  secretObjects:
    - secretName: {{ $.Values.existingSecret }}
      type: Opaque
      data:
      {{- range $name, $key := .objects }}
        - { objectName: {{ $name }}, key: {{ $key }} }
      {{- end }}
{{- end }}
{{- end }}
