# Generated by Django 5.2.17 on 2026-09-11 09:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisNotebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "summary",
                    models.CharField(blank=True, help_text="One-line description for cards", max_length=300),
                ),
                ("description", models.TextField(blank=True, help_text="Markdown allowed")),
                (
                    "use_case",
                    models.CharField(
                        choices=[
                            ("uc1", "Risk exposure"),
                            ("uc2", "Impact estimation"),
                            ("uc3", "Response prioritisation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[("local", "Local templates directory"), ("git", "Git repository")],
                        default="local",
                        max_length=10,
                    ),
                ),
                ("source_repo", models.URLField(blank=True, help_text="Git URL when source_kind=git")),
                (
                    "source_ref",
                    models.CharField(blank=True, help_text="Branch, tag or commit", max_length=120),
                ),
                (
                    "notebook_path",
                    models.CharField(
                        help_text="Path to the .ipynb relative to the templates dir (local) or repo root (git)",
                        max_length=300,
                    ),
                ),
                ("version", models.CharField(blank=True, max_length=40)),
                (
                    "parameter_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema (object) describing the user-facing parameters",
                    ),
                ),
                (
                    "requires_area",
                    models.BooleanField(default=True, help_text="Run needs a target admin area"),
                ),
                (
                    "area_levels",
                    models.JSONField(
                        blank=True, default=list, help_text="Allowed admin levels, e.g. [1, 2]; empty = any"
                    ),
                ),
                (
                    "requires_event",
                    models.BooleanField(default=False, help_text="Run needs a Montandon event"),
                ),
                (
                    "supports_writeback",
                    models.BooleanField(
                        default=False, help_text="Notebook produces a STAC collection to write back"
                    ),
                ),
                ("estimated_runtime_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hazards",
                    models.ManyToManyField(blank=True, related_name="notebooks", to="catalog.hazard"),
                ),
            ],
            options={
                "ordering": ["use_case", "title"],
            },
        ),
        migrations.CreateModel(
            name="RunBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (UI)"),
                            ("api", "API"),
                            ("auto", "Automatic (event)"),
                            ("cli", "Command line"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="notebooks.analysisnotebook",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotebookRun",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("fetching", "Fetching inputs"),
                            ("executing", "Executing notebook"),
                            ("rendering", "Rendering HTML"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=12,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, help_text="User-facing parameters (validated)"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual (UI)"),
                            ("api", "API"),
                            ("auto", "Automatic (event)"),
                            ("cli", "Command line"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("notify_emails", models.JSONField(blank=True, default=list)),
                ("celery_task_id", models.CharField(blank=True, max_length=64)),
                (
                    "progress",
                    models.JSONField(
                        blank=True, default=dict, help_text="{'cell': 8, 'total': 23, 'message': ...}"
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "output_prefix",
                    models.CharField(blank=True, help_text="Storage key prefix for this run", max_length=300),
                ),
                (
                    "output_url",
                    models.URLField(blank=True, help_text="Published HTML entry point", max_length=600),
                ),
                (
                    "notebook_url",
                    models.URLField(blank=True, help_text="Executed .ipynb for download", max_length=600),
                ),
                (
                    "artifacts",
                    models.JSONField(
                        blank=True, default=dict, help_text="Other published files: {name: url}"
                    ),
                ),
                (
                    "writeback_status",
                    models.CharField(
                        choices=[
                            ("none", "Not applicable"),
                            ("pending", "Pending"),
                            ("done", "Written back"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "writeback_ref",
                    models.CharField(
                        blank=True, help_text="Collection id / URL written to Montandon", max_length=400
                    ),
                ),
                ("writeback_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="catalog.adminarea",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="events.event",
                    ),
                ),
                (
                    "hazard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="catalog.hazard",
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="notebooks.analysisnotebook",
                    ),
                ),
                (
                    "trigger_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="events.eventtriggerrule",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notebook_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="notebooks.runbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RunLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("level", models.CharField(default="info", max_length=10)),
                ("message", models.TextField()),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="notebooks.notebookrun",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "run log entries",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
