# Generated by Django 5.2.17 on 2026-09-11 09:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("iso3", models.CharField(max_length=3, primary_key=True, serialize=False)),
                ("iso2", models.CharField(blank=True, max_length=2)),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name_plural": "countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Hazard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, help_text="Emoji shown in the UI", max_length=8)),
                ("color", models.CharField(blank=True, help_text="Hex colour used for badges", max_length=7)),
                (
                    "monty_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Montandon hazard code prefixes that map to this hazard, e.g. ['nat-hyd-flo'].",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="AdminArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Stable identifier from the source, e.g. GADM GID or P-code", max_length=64
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("gadm", "GADM"),
                            ("cod", "COD (OCHA Common Operational Datasets)"),
                            ("custom", "Custom"),
                        ],
                        default="gadm",
                        max_length=16,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
                ),
                (
                    "bbox",
                    models.JSONField(blank=True, help_text="[minx, miny, maxx, maxy] in WGS84", null=True),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
                ),
                ("area_km2", models.FloatField(blank=True, null=True)),
                (
                    "properties",
                    models.JSONField(blank=True, default=dict, help_text="Extra attributes from the source"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.adminarea",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas",
                        to="catalog.country",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "level", "name"],
                "indexes": [
                    models.Index(fields=["country", "level"], name="catalog_adm_country_978507_idx"),
                    models.Index(fields=["level"], name="catalog_adm_level_61629f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("source", "code"), name="uniq_area_source_code")
                ],
            },
        ),
    ]
