# Generated by Django 5.2.17 on 2026-09-11 09:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollerState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("collection", models.CharField(max_length=120, unique=True)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_item_datetime", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("items_seen", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("stac_id", models.CharField(max_length=200)),
                ("collection", models.CharField(db_index=True, max_length=120)),
                ("monty_corr_id", models.CharField(blank=True, db_index=True, max_length=200)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("hazard_codes", models.JSONField(blank=True, default=list)),
                ("country_codes", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, max_length=120)),
                ("occurred_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("item_updated_at", models.DateTimeField(blank=True, null=True)),
                ("bbox", models.JSONField(blank=True, null=True)),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ("raw", models.JSONField(blank=True, default=dict, help_text="The STAC item as fetched")),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hazard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="catalog.hazard",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-first_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="EventRunLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("item_updated_at", models.DateTimeField(blank=True, null=True)),
                ("fired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_links",
                        to="events.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTriggerRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "collections",
                    models.JSONField(
                        default=list, help_text="STAC collections to watch, e.g. ['reference-events']"
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True, default=list, help_text="Only items with one of these roles (empty = any)"
                    ),
                ),
                (
                    "country_codes",
                    models.JSONField(
                        blank=True, default=list, help_text="Only these ISO3 countries (empty = any)"
                    ),
                ),
                (
                    "parameter_template",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameters for the run. String values may use Jinja, e.g. {{ event.monty_corr_id }}.",
                    ),
                ),
                (
                    "area_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Fan out over all areas at this admin level in the event's countries; null = country-level run",
                        null=True,
                    ),
                ),
                (
                    "rerun_on_update",
                    models.BooleanField(default=False, help_text="Re-run when the STAC item is updated"),
                ),
                ("notify_emails", models.JSONField(blank=True, default=list)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hazards",
                    models.ManyToManyField(
                        blank=True, help_text="Only these hazards (empty = any)", to="catalog.hazard"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
