# Generated by Django 5.2.17 on 2026-09-11 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("notebooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtriggerrule",
            name="notebook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trigger_rules",
                to="notebooks.analysisnotebook",
            ),
        ),
        migrations.AddField(
            model_name="eventrunlink",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_links",
                to="events.eventtriggerrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("collection", "stac_id"), name="uniq_event_collection_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventrunlink",
            constraint=models.UniqueConstraint(fields=("event", "rule"), name="uniq_event_rule"),
        ),
    ]
